version: '3.8'

services:
  ai-news:
    build: .
    container_name: ai_news_app
    restart: unless-stopped
    
    # 数据卷映射 - 持久化数据
    volumes:
      - ./data:/app/data
      - ./config/config.yaml:/app/config/config.yaml:ro  # 只读配置文件
      - ./logs:/app/data/logs
    
    # 端口映射（如果需要Web界面）
    ports:
      - "8080:8080"
    
    # 环境变量（可选，如果需要覆盖配置）
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 依赖服务（如果将来需要数据库）
    # depends_on:
    #   - redis
    #   - postgres
    
    # 网络配置
    networks:
      - ai_news_network
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # 可选：添加监控服务
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: ai_news_watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 3600 --cleanup ai_news_app
  #   networks:
  #     - ai_news_network

# 网络配置
networks:
  ai_news_network:
    driver: bridge

# 数据卷配置
volumes:
  ai_news_data:
    driver: local 